### PR TITLE
Adding Wurlitzer as a dependency

### PR DESCRIPTION
**Pull request by jayendra13**
To fix https://github.com/Calysto/matlab_kernel/issues/104 and other wurlitzer related issues

### CODE REVIEW

**Comment by blink1073** [comment]
LGTM, thanks!

**Comment by blink1073** [comment]
Released as 0.16.0

**Comment by auneri** [comment]
Thank you! One small bug however, wurlitzer is only available on unix.

**Comment by blink1073** [comment]
Thanks for the heads up @auneri!  I pushed 0.16.1.

**Comment by jayendra13** [comment]
Oh!! I missed that thanks @auneri.

**Pull request merged**
