### PR TITLE
Drop compulsory dependency on pymatbridge.

### PR DESCRIPTION
**Pull request by anntzer**
See #39.

### CODE REVIEW

**Comment by blink1073** [comment]
Sorry @anntzer, I had forgotten to push some changes I made a few days ago and now there is a merge conflict.

**Comment by blink1073** [comment]
I am increasingly unable to maintain this library, as I do not have a Matlab install and now I cannot get even pymatbridge to work.  @anntzer, would you be willing to take on the long term maintenance of this library and support only the native engine?

**Comment by anntzer** [comment]
done.

**Comment by anntzer** [comment]
I guess dropping pymatbridge would also mean dropping support for octave?

**Comment by blink1073** [comment]
I maintain the Octave Kernel, which does not rely on pymatbridge.

**Comment by blink1073** [comment]
https://github.com/Calysto/octave_kernel

**Comment by anntzer** [comment]
Let's do it then.

**Comment by arokem** [comment]
FWIW, I am +1 to dropping the pymatbridge requirement. There are some unresolved issues with newer versions of Matlab (e.g., https://github.com/arokem/python-matlab-bridge/issues/244), and I have very little bandwidth to resolve these (and less and less need for my own purposes). 

Unless I am understanding something, it seems to me that the Matlab Python interface should eventually make the work in pymatbridge obsolete.

**Comment by blink1073** [comment]
@anntzer, getting you set up now, what is your PyPI username?

**Comment by blink1073** [comment]
I added `anntzer` on PyPI as an owner, and you are an owner here.  Thanks so much!

**Comment by anntzer** [comment]
You found me :)

**Pull request merged**
