### PR TITLE
Switch to new kernelspec install.

### PR DESCRIPTION
**Pull request by anntzer**
All's in the title.

### CODE REVIEW

**Comment by blink1073** [comment]
This is great!  Can you please update the README to reflect `python -m matlab_kernel install` (remove the period)?

**Comment by anntzer** [comment]
Squeezed in a few extra edits to the README.

**Comment by blink1073** [comment]
Sweet, thanks!

**Comment by blink1073** [comment]
Released as `0.10.0`.

**Comment by auneri** [comment]
Looks like the `MatlabKernel.run_as_main` method is missing?

**Comment by anntzer** [comment]
Should be provided by metakernel 0.13.1.

**Comment by auneri** [comment]
Ah I see, should probably update `flit.ini` with the new requirement then?

**Comment by anntzer** [comment]
Indeed, I missed that.

**Comment by blink1073** [comment]
Fixed in `v0.10.1`

**Pull request merged**
