### PR TITLE
returning ExceptionWrapper object if excution halts with error

### PR DESCRIPTION
**Pull request by jayendra13**
To resolve
https://github.com/Calysto/matlab_kernel/issues/113

### CODE REVIEW

**Comment by blink1073** [comment]
Looks good, thank you!

**Comment by blink1073** [comment]
Released to PyPI as 0.15.2

**Comment by jayendra13** [comment]
whoa great!!

**Comment by dsblank** [comment]
Thanks, @jayendra13 ! And thanks @blink1073 for the quick update!

**Pull request merged**
