### PR TITLE
FIX: issue #146 (No output in Matlab 2020b)

### PR DESCRIPTION
**Pull request by davide84**

### CODE REVIEW

**Comment by dsblank** [comment]
@davide84 Any idea of when this changed? Will it break with other versions? What versions is this know to work? Maybe we need something in the front README that mentions what version it is know to work?

**Comment by davide84** [comment]
You are right. I'll try to get some more information.

**Comment by davide84** [comment]
Ok, first thing I understood is that the change is related to the Matlab engine, not to Python in general.

According to Matlab documentation:
> eng = matlab.engine.start_matlab(async) starts MATLAB asynchronously if async is True. Not recommended. Use the background argument instead. Do not use for Python Version 3.7.
> For Python Version 3.7, async is a keyword and cannot be used as an argument for matlab.engine.start_matlab. Use the background argument instead for all supported versions of Python.
https://ch.mathworks.com/help/matlab/apiref/matlab.engine.start_matlab.html

My understanding is that 'background' should not only be the default nowadays, but it it also recommended for all versions of Python with Matlab 2020b.

As for previous Matlab versions, according to my research the 'background' keyword was introduced in Matlab R2017b:
https://ch.mathworks.com/help/releases/R2017b/matlab/apiref/matlab.engine.start_matlab.html?s_tid=doc_ta
and it was not present in R2017a:
https://ch.mathworks.com/help/releases/R2017a/matlab/apiref/matlab.engine.start_matlab.html?s_tid=doc_ta

**Comment by dsblank** [comment]
Looks good (even tough I don't have matlab :+1:  )!

**Review by blink1073 — APPROVED** [review]
Thanks!

**Comment by blink1073** [comment]
Released as 0.16.10.

**Pull request merged**
