### PR TITLE
Add handling of width and height options

### PR DESCRIPTION
**Pull request by blink1073**
From https://github.com/Calysto/metakernel/pull/118.

### CODE REVIEW

**Comment by anntzer** [comment]
@blink1073 I ended up setting up my own rewrite (https://github.com/anntzer/matlab_kernel) which does not depend on metakernel at all and does not provide support for inline graphics (because I rarely use the notebook, and the MATLAB live editor probably works better for that purpose anyways...) so I won't maintain this repo anymore.

**Comment by blink1073** [comment]
Hi @anntzer, no worries.  Are you interested in making that fork the "official" kernel?  That would entail releasing it from your fork to PyPI.  I would update https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages and deprecate this repo to point to your fork.

**Comment by dsblank** [comment]
Let's go ahead and live this repo, as it has a different niche (metakernel-based, giving magics, shell, etc.)

**Comment by blink1073** [comment]
@dsblank, I am unable to support this repo because I don't have a Matlab license.  I tried limping along without one, but it has proved to be sustainable.

**Comment by anntzer** [comment]
I don't feel very strongly either way: if @dsblank really wants to keep a metakernel-based MATLAB kernel I'll just keep my own for private use; conversely, following @blink1073's proposal I can move my version to this repo as well, although I will almost certainly want to drop support for Python <3.5 (given that this should easily be installable in its own conda env / venv anyways, independently of anything else (including jupyter itself)).

To be honest, I don't really think a MATLAB kernel benefits from the metakernel magics, because most such magics are already available as MATLAB functions: cd, download (websave), edit, help, ls, shell (!...) (I haven't tried to make an exhaustive list).  Likewise, the helper functions that metakernel provides, say, for printing, are easily replaced by direct calls to the jupyter API.

**Comment by dsblank** [comment]
@blink1073 I understand; I'd like to keep it here, even if we only accept PRs for now.

@anntzer No problem, but this organization (Calysto) is built around Jupyter and Python utilities. There are people that use Calysto.matlab_kernel because it does have a common set of magics with other Metakernel-based languages. For example, in the classroom we can provide a common set of tools (including running Matlab in parallel). But you should rename yours so one can install and run both.

**Comment by anntzer** [comment]
To be honest I don't think it's making any MATLAB student a favor to teach them using %shell instead of the normal ! to run a shell command, and so on.  So if anything I would think that my version is the one that should keep the name, as it exposes exactly the same language as MATLAB, simply in a jupyter frontend, whereas this one exposes the Calysto dialect of MATLAB (I do not mean this confrontationally; I really think this).

However, if there are other things that I can change that would make my kernel more suitable for your use (e.g. running MATLAB in parallel, whatever that means), I could look into that.

**Comment by dsblank** [comment]
@anntzer Metakernel has many magics that can be used in research and the classroom. The only reason for matlab_kernel to be in this organization is that it is based on Metakernel.

BTW, one can run and communicate with multiple versions of any Metakernel language using the %parallel and %px magics. But you don't need to reinvent the wheel; matlab_kernel already supports this, and many other magics.

**Comment by anntzer** [comment]
OK, I'll leave things as they are then.

**Pull request merged**
